export const C = {
  cream: '#fdfcfb',
  creamDark: '#ede8e0',
  ink: '#1A2A4A',
  inkLight: '#3D5A80',
  sage: '#4A90D9',
  sageDark: '#3A7BC8',
  sagePale: '#E8F0FE',
  sageLight: '#A8C8EE',
  stone: '#8DA4C0',
  muted: '#6B82A0',
  mutedLight: '#B8C8E0',
  white: '#ffffff',
  warn: '#d97706',
  success: '#4A90D9',
  error: '#dc2626',
}

export const S = {
  card: {
    background: C.white,
    borderRadius: 16,
    border: `1px solid ${C.creamDark}`,
    boxShadow: '0 1px 8px rgba(26,42,74,0.06)',
  },
  input: {
    width: '100%' as const,
    padding: '12px 14px',
    borderRadius: 10,
    border: `1.5px solid ${C.creamDark}`,
    background: C.cream,
    fontSize: 14,
    color: C.ink,
    outline: 'none' as const,
    boxSizing: 'border-box' as const,
    fontFamily: 'inherit',
  },
  btnPrimary: {
    padding: '12px 20px',
    borderRadius: 12,
    border: 'none',
    background: C.sage,
    color: C.white,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.18s',
  },
  btnGhost: {
    padding: '10px 18px',
    borderRadius: 12,
    border: `1.5px solid ${C.creamDark}`,
    background: 'transparent',
    color: C.muted,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnDanger: {
    padding: '10px 18px',
    borderRadius: 12,
    border: `1.5px solid ${C.error}40`,
    background: `${C.error}0a`,
    color: C.error,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  label: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    color: C.muted,
    marginBottom: 6,
    letterSpacing: 0.5,
  },
}

export const fonts = {
  display: 'Inter, system-ui, sans-serif',
  body: 'Inter, system-ui, sans-serif',
  mono: '"JetBrains Mono", "Fira Code", monospace',
}
