export const C = {
  cream: '#fdfcfb',
  creamDark: '#ede8e0',
  ink: '#1e293b',
  inkLight: '#475569',
  sage: '#6B8F71',
  sageDark: '#4a6b50',
  sagePale: '#e8f0e9',
  sageLight: '#a8c0ab',
  stone: '#94a3b8',
  muted: '#64748b',
  mutedLight: '#cbd5e1',
  white: '#ffffff',
  warn: '#d97706',
  success: '#5a8a60',
  error: '#dc2626',
}

export const S = {
  card: {
    background: C.white,
    borderRadius: 16,
    border: `1px solid ${C.creamDark}`,
    boxShadow: '0 1px 8px rgba(30,41,59,0.06)',
  },
  input: {
    width: '100%' as const,
    padding: '12px 14px',
    borderRadius: 10,
    border: `1.5px solid ${C.creamDark}`,
    background: C.cream,
    fontSize: 14,
    color: C.ink,
    outline: 'none' as const,
    boxSizing: 'border-box' as const,
    fontFamily: 'inherit',
  },
  btnPrimary: {
    padding: '12px 20px',
    borderRadius: 12,
    border: 'none',
    background: C.sage,
    color: C.white,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.18s',
  },
  btnGhost: {
    padding: '10px 18px',
    borderRadius: 12,
    border: `1.5px solid ${C.creamDark}`,
    background: 'transparent',
    color: C.muted,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnDanger: {
    padding: '10px 18px',
    borderRadius: 12,
    border: `1.5px solid ${C.error}40`,
    background: `${C.error}0a`,
    color: C.error,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  label: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    color: C.muted,
    marginBottom: 6,
    letterSpacing: 0.5,
  },
}

export const fonts = {
  display: 'Inter, system-ui, sans-serif',
  body: 'Inter, system-ui, sans-serif',
  mono: '"JetBrains Mono", "Fira Code", monospace',
}
